### ISSUE TITLE
error in cluster v0.3.7

### ISSUE THREAD

**Issue by nextgenusfs** [nextgenusfs/ufits#5]
Since i've upgraded to version 0.3.7 (from 0.2.8) i get this error using the 'cluster' script, do you think i need to uprgade any dependencies to fix this?
```
$ ufits cluster -i ITS.rarify.2.fq  --uchime_ref ITS2 --cleanup
-------------------------------------------------------
[03:03:35 PM]: Operating system: linux2, ufits v.0.3.7
[03:03:35 PM]: USEARCH version: usearch v8.1.1861_i86linux32
[03:03:35 PM]: vsearch detected, will use for filtering
[03:03:35 PM]: Loading FASTQ Records
[03:03:36 PM]: 1,390,913 reads (843.8 MB)
[03:03:36 PM]: Quality Filtering, expected errors < 1.0
Traceback (most recent call last):
  File "/home/tvv/Bureau/ufits/bin/ufits-OTU_cluster.py", line 95, in <module>
    subprocess.call(['vsearch', '--fastq_filter', args.FASTQ, '--fastq_maxee', str(args.maxee), '--fastqout', filter_out, '--fastaout', filter_fasta, '--fastq_qmax', '45'], stdout = FNULL, stderr = FNULL)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory
```

**Comment by nextgenusfs** [comment]
This is a vsearch compatibility issue.  upgrading to at least version 1.9.1 fixes the problem.  Need to determine which version of vsearch is non functional to build in a version check for UFITS to default to python if less than X version installed.

**Comment by nextgenusfs** [comment]
From the docs of vsearch, it looks like the `--fastq_filter` option was added in version 1.9.0.  So will update script to make sure >= than 1.9.1 is installed
